annotate_path: /path/to/IGU_CHANGEseq/changeseq/data/ncbiRefSeq.bed.gz
reference_genome:  /path/to/hg38.fa
changeseq_adapter: CTGTCTCTTATACACATCTACGTAGATGTGTATAAGAGACAG
cutadapt: cutadapt
njobs: 6
AG_read: 1
samtools: samtools
window_size: 30
bwa: bwa
dedup_umi: FALSE
analysis_folder: data/StandardOutput/
normalize: median
read_length: 151
read_threshold: 6
merged_analysis: FALSE
mismatch_threshold: 6
bulge_threshold: 1
edist_threshold: 7
variant_analysis: FALSE
bc_pattern: None
start_threshold: 1
mapq_threshold: 40
PAM: NGG

#Cas9 params:
gap_threshold: 3
search_radius: 30

# BE params
# ideal
# BEsearch_radius: 10
# BEmodel_min_overlap: 2
# BEmodel_max_overlap: 15
BEsearch_radius: 10
BEmodel_min_overlap: 2
BEmodel_max_overlap: 15
samples:
  TEST:
    target: GAGTCCGAGCAGAAGAAGAANGG
    read1: data/input/TEST_R1_001.fastq.gz
    read2: data/input/TEST_R2_001.fastq.gz
    controlread1: data/input/TEST_control_R1_001.fastq.gz
    controlread2: data/input/TEST_control_R2_001.fastq.gz
    description: TestCell
