annotate_path: /home/thudson/projects/IGU_CHANGEseq/changeseq/data/ncbiRefSeq.bed.gz
reference_genome:  /groups/clinical/projects/clinical_shared_data/hg38/hg38.fa
changeseq_adapter: CTGTCTCTTATACACATCT
cutadapt: cutadapt
njobs: 6
AG_read: 1
samtools: samtools
window_size: 30
bwa: bwa
dedup_umi: FALSE
analysis_folder: data/StandardOutput/
search_radius: 30
normalize: median
read_threshold: 6
gap_threshold: 3
merged_analysis: FALSE
mismatch_threshold: 6
variant_analysis: FALSE
bc_pattern: None
start_threshold: 1
mapq_threshold: 40
PAM: NGG
samples:
  TEST:
    target: GAGTCCGAGCAGAAGAAGAANGG
    read1: data/input/TEST_R1_001.fastq.gz
    read2: data/input/TEST_R2_001.fastq.gz
    controlread1: data/input/TEST_control_R1_001.fastq.gz
    controlread2: data/input/TEST_control_R2_001.fastq.gz
    description: TestCell
